api_v1_upload_image:
    path: /api/v1/upload/image
    methods: POST
    controller: App\Action\Upload\UploadImageAction

api_v1_upload_video:
    path: /api/v1/upload/video
    methods: POST
    controller: App\Action\Upload\UploadVideoAction

api_v1_upload_file:
    path: /api/v1/upload/file
    methods: POST
    controller: App\Action\Upload\UploadFileAction

download_file:
    path: /dl/{path}
    methods: GET
    controller: App\Action\Download\DownloadFileAction
    requirements:
        path: '.+\.[a-z]{3,4}'
