api_v1_upload_image:
    path: /api/v1/upload/image
    methods: POST
    controller: App\Action\Upload\UploadImageAction

api_v1_upload_video:
    path: /api/v1/upload/video
    methods: POST
    controller: App\Action\Upload\UploadVideoAction

api_v1_upload_file:
    path: /api/v1/upload/file
    methods: POST
    controller: App\Action\Upload\UploadFileAction

download_image:
    path: /images/{path}
    methods: GET
    controller: App\Action\Download\DownloadImageAction
    requirements:
        path: '.+\.[a-z]{3,4}'

download_video:
    path: /videos/{path}
    methods: GET
    controller: App\Action\Download\DownloadVideoAction
    requirements:
        path: '.+\..{2,5}'

download_file:
    path: /files/{path}
    methods: GET
    controller: App\Action\Download\DownloadFileAction
    requirements:
        path: '.+\..{2,5}'